name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Project Dependencies
        run: npm ci

      - name: Generate Code Statistics with Elocuent
        run: |
          mkdir -p meta
          npx elocuent -d . -o meta/loc.csv

      - name: Commit and Push Generated CSV File
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase
          git add -f meta/loc.csv
          git commit -m "Update code statistics" || echo "No changes to commit"
          git push origin main

